#!/bin/bash

function hc() {
    herbstclient "$@"
}

hc emit_hook reload

hc pad 0 12 0 0

# scripts
hfsdir="$HOME/.config/herbstluftwm/scripts"

# remove all existing keybindings
hc keyunbind --all

# set mod key
Mod=Mod4

# tags
TAG_NAMES=( "1:ETC" "2:WEB" "3:DEV" "4:IMG" "5:VID" )
TAG_KEYS=( {1..5} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# keybindings
hc keybind $Mod-Shift-q spawn xfce4-session-logout
hc keybind $Mod-Shift-r spawn $hfsdir/reload.sh
hc keybind $Mod-Shift-c close
hc keybind $Mod-f spawn catfish --path=/
hc keybind $Mod-i spawn firefox
hc keybind $Mod-g spawn geany
hc keybind $Mod-Shift-g spawn gimp
hc keybind $Mod-l spawn libreoffice
hc keybind $Mod-m spawn google-play-music-desktop-player
hc keybind $Mod-v spawn vlc
hc keybind $Mod-s spawn gksu synaptic
hc keybind $Mod-t spawn thunar
hc keybind $Mod-Shift-t spawn gksu thunar
hc keybind Menu spawn urxvt
hc keybind $Mod-Menu spawn rofi -show run -columns 2 -fullscreen
hc keybind $Mod-Shift-Menu spawn rofi -show window -fullscreen
hc keybind $Mod-KP_Add spawn $hfsdir/compton.sh

# layouting
hc keybind $Mod-KP_Delete remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-semicolon split vertical 0.5
hc keybind $Mod-apostrophe split horizontal 0.5
hc keybind $Mod-Shift-m fullscreen toggle
hc keybind $Mod-comma floating toggle
hc keybind $Mod-period pseudotile toggle

# resizing
RESIZESTEP=0.025
hc keybind $Mod-Control-Left resize left +$RESIZESTEP
hc keybind $Mod-Control-Down resize down +$RESIZESTEP
hc keybind $Mod-Control-Up resize up +$RESIZESTEP
hc keybind $Mod-Control-Right resize right +$RESIZESTEP

# focus
hc keybind $Mod-Left focus left
hc keybind $Mod-Down focus down
hc keybind $Mod-Up focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-Shift-Left shift left
hc keybind $Mod-Shift-Down shift down
hc keybind $Mod-Shift-Up shift up
hc keybind $Mod-Shift-Right shift right

hc keybind $Mod-Alt-Left chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
hc keybind $Mod-Alt-Down chain , lock , shift_to_monitor -d , focus_monitor -d , unlock
hc keybind $Mod-Alt-Up chain , lock , shift_to_monitor -u , focus_monitor -u , unlock
hc keybind $Mod-Alt-Right chain , lock , shift_to_monitor -r , focus_monitor -r , unlock

# fn keys
#hc keybind XF86Tools spawn toggletouchpad
hc keybind XF86Calculator spawn galculator
hc keybind Print spawn scrot '%Y-%m-%d_%H-%M-%S.png' -e 'mv $f ~/Pictures/Screenshots &amp; mirage ~/Pictures/Screenshots/$f' -q 100
hc keybind $Mod-Print spawn scrot '%Y-%m-%d_%H-%M-%S.png' -e 'mv $f ~/Pictures/Screenshots &amp; mirage ~/Pictures/Screenshots/$f' -q 100 -u -b
hc keybind XF86WebCam spawn guvcview

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# colors
hc set frame_bg_transparent 1
hc set frame_border_width 0
hc set window_border_width 2
hc set window_border_inner_width 0
hc set window_border_normal_color '#374244'
hc set window_border_active_color '#d3c2aa'
hc set always_show_frame 0
hc set frame_gap 20
hc set frame_active_opacity 0
hc set frame_normal_opacity 0
hc set frame_transparent_width 0
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

# multi-monitors
hc set auto_detect_monitors 1

# rules
hc unrule -F
hc rule focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

#hc rule class=Insync.py manage=off

# unlock, just to be sure
hc unlock

# autostart
$hfsdir/startup.sh &

# tag 4
hc rule class=Gimp tag='4:IMG'
